
copper-items:
  copper-axe:
    enable: true
    attack-damage: 9.5
    attack-speed: 0.8
  copper-sword:
    enable: true
    attack-damage: 6.5
    attack-speed: 1.6
  copper-pickaxe:
    enable: true
  copper-shovel:
    enable: true
  copper-hoe:
    enable: true

copper-armor:
  copper-helmet:
    enable: true
    armor: 2
  copper-chestplate:
    enable: true
    armor: 6
  copper-leggings:
    enable: true
    armor: 4
  copper-boots:
    enable: true
    armor: 2
language: en_US