name: CopperItems
version: '2.1'
main: copper.items.items.copper.Items.CopperItems
api-version: 1.21.5
authors: [ Greefox ]
description: Adds craftable copper items!
load: POSTWORLD
commands:
  givecopperitem:
    description: "Gives a player a copper item!"
    usage: /<command> <item> <player>