#en_US, ES, RU, GE (german) or UK (ukrainian), more languages coming soon!
language: en_US
enable-resource-pack: true
items:
  axe:
    enable: true
    attack-damage: 9.5
    attack-speed: 0.8
  hoe:
    enable: true
  pickaxe:
    enable: true
  shovel:
    enable: true
  sword:
    enable: true
    attack-damage: 6.5
    attack-speed: 1.6
armor:
  helmet:
    enable: true
    armor: 2
  chestplate:
    enable: true
    armor: 6
  leggings:
    enable: true
    armor: 4
  boots:
    enable: true
    armor: 2